/**
 * Speaker Validation Utilities
 * Shared patterns for identifying generic/placeholder speaker names
 * Used by both main process and renderer process
 */

/**
 * Patterns that match generic/placeholder speaker names
 * These are auto-generated by transcription services and don't represent real names
 */
const GENERIC_SPEAKER_PATTERNS = [
  /^speaker\s*[a-z0-9]$/i, // "Speaker A", "Speaker B", "Speaker 1"
  /^SPK[-_][a-z0-9]+$/i, // "SPK-abc123", "SPK_xyz"
  /^spk_\d+$/i, // "spk_1", "spk_2"
  /^SPEAKER_\d+$/i, // "SPEAKER_1", "SPEAKER_2"
  /^S\d+$/i, // "S1", "S2"
  /^unknown\s*speaker$/i, // "Unknown Speaker"
];

/**
 * Check if a speaker name is a generic/placeholder name
 * Generic names are auto-generated by transcription services and shouldn't be:
 * - Saved as persistent mappings (they're not consistent across transcripts)
 * - Used for duplicate detection (comparing "Speaker A" to "Speaker B" is meaningless)
 *
 * @param {string} name - Speaker name to check
 * @returns {boolean} True if it's a generic/placeholder name
 */
function isGenericSpeakerName(name) {
  if (!name) return true;
  return GENERIC_SPEAKER_PATTERNS.some(pattern => pattern.test(name.trim()));
}

// Export for both CommonJS (main process) and ES modules (renderer)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    GENERIC_SPEAKER_PATTERNS,
    isGenericSpeakerName,
  };
}

// ES module export for renderer
export { GENERIC_SPEAKER_PATTERNS, isGenericSpeakerName };
